# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='category', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='country', editable=False, max_length=50, verbose_name='entity type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'country (pricing)',
                'verbose_name_plural': 'countries (pricing)',
            },
        ),
        migrations.CreateModel(
            name='CreativeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='creative_type', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'creative type',
                'verbose_name_plural': 'creative types',
            },
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='effort', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'effort',
                'verbose_name_plural': 'efforts',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='goal', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'goal',
                'verbose_name_plural': 'goals',
            },
        ),
        migrations.CreateModel(
            name='L11Custom4',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l11_custom4', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 4 (L11)',
                'verbose_name_plural': 'custom labels 4 (L11)',
            },
        ),
        migrations.CreateModel(
            name='L13Custom5',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l13_custom5', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 5 (L13)',
                'verbose_name_plural': 'custom labels 5 (L13)',
            },
        ),
        migrations.CreateModel(
            name='L15Custom6',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l15_custom6', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 6 (L15)',
                'verbose_name_plural': 'custom labels 6 (L15)',
            },
        ),
        migrations.CreateModel(
            name='L16Custom7',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l16_custom7', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 7 (L16)',
                'verbose_name_plural': 'custom labels 7 (L16)',
            },
        ),
        migrations.CreateModel(
            name='L17Custom8',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l17_custom8', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 8 (L17)',
                'verbose_name_plural': 'custom labels 8 (L17)',
            },
        ),
        migrations.CreateModel(
            name='L19Custom9',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l19_custom9', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 9 (L19)',
                'verbose_name_plural': 'custom labels 9 (L19)',
            },
        ),
        migrations.CreateModel(
            name='L20Custom10',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l20_custom10', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 10 (L20)',
                'verbose_name_plural': 'custom labels 10 (L20)',
            },
        ),
        migrations.CreateModel(
            name='L5Custom1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l5_custom1', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 1 (L5)',
                'verbose_name_plural': 'custom labels 1 (L5)',
            },
        ),
        migrations.CreateModel(
            name='L8Custom2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l8_custom2', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 2 (L8)',
                'verbose_name_plural': 'custom labels 2 (L8)',
            },
        ),
        migrations.CreateModel(
            name='L9Custom3',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='l9_custom3', editable=False, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'custom label 3 (L9)',
                'verbose_name_plural': 'custom labels 3 (L9)',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='language', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='MediaUnitType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'media unit type',
                'verbose_name_plural': 'media unit types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='product', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='publisher', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='tactic', editable=False, max_length=50, verbose_name='entity type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tactic',
                'verbose_name_plural': 'tactics',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('goal', 'Goal'), ('publisher', 'Publisher'), ('tactic', 'Tactic'), ('creative_type', 'Creative Type'), ('country', 'Country'), ('performance_pricing_model', 'Performance Pricing Model'), ('performance_pricing_model_value', 'Performance Pricing Model Value'), ('effort', 'Effort'), ('category', 'Category'), ('product', 'Product'), ('language', 'Language'), ('l5_custom1', 'Custom Label 1'), ('l8_custom2', 'Custom Label 2'), ('l9_custom3', 'Custom Label 3'), ('l11_custom4', 'Custom Label 4'), ('l13_custom5', 'Custom Label 5'), ('l15_custom6', 'Custom Label 6'), ('l16_custom7', 'Custom Label 7'), ('l17_custom8', 'Custom Label 8'), ('l19_custom9', 'Custom Label 9'), ('l20_custom10', 'Custom Label 10')], db_index=True, max_length=50, verbose_name='entity type')),
                ('entity_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='entity name')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.costcenter', verbose_name='cost center')),
                ('owner_advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_entities', to='core.advertiser', verbose_name='owner advertiser')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['entity_type', 'entity_name'],
            },
        ),
        migrations.CreateModel(
            name='AdvertiserEntityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='blocked at')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_entities', to='core.advertiser', verbose_name='advertiser')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_advertisers', to='entities.entity', verbose_name='entity')),
            ],
            options={
                'verbose_name': 'advertiser entity block',
                'verbose_name_plural': 'advertiser entity blocks',
            },
        ),
        migrations.CreateModel(
            name='GoalEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='entities.effort')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effort_links', to='entities.goal')),
            ],
        ),
        migrations.CreateModel(
            name='PerformancePricingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='performance_pricing_model', editable=False, max_length=50, verbose_name='entity type')),
                ('payment_type', models.CharField(default='media_unit_type', max_length=20, verbose_name='payment type')),
                ('default_payment_method', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid'), ('CREDIT', 'Credit')], default='POSTPAID', max_length=20, verbose_name='default payment method')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_pricing_models', to='core.costcenter', verbose_name='cost center')),
                ('media_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_models', to='entities.mediaunittype', verbose_name='media unit type')),
            ],
            options={
                'verbose_name': 'performance pricing model',
                'verbose_name_plural': 'performance pricing models',
            },
        ),
        migrations.CreateModel(
            name='CountryPerformancePricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_model_links', to='entities.country')),
                ('performance_pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_links', to='entities.performancepricingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PerformancePricingModelValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(default='performance_pricing_model_value', editable=False, max_length=50, verbose_name='entity type')),
                ('value_micros', models.BigIntegerField(help_text='Price value in micros (1 unit = 1,000,000 micros)', verbose_name='value (micros)')),
                ('start_date', models.DateField(blank=True, help_text='Start date for this pricing value', null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='End date for this pricing value', null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('performance_pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='entities.performancepricingmodel', verbose_name='performance pricing model')),
            ],
            options={
                'verbose_name': 'performance pricing model value',
                'verbose_name_plural': 'performance pricing model values',
            },
        ),
        migrations.CreateModel(
            name='PerformancePricingModelValue_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_links', to='entities.performancepricingmodel')),
                ('performance_pricing_model_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_links', to='entities.performancepricingmodelvalue')),
            ],
            options={
                'db_table': 'entities_perf_pricing_model_value',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='entities.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='entities.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='entities.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_links', to='entities.product')),
            ],
        ),
        migrations.CreateModel(
            name='GoalPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_links', to='entities.goal')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='entities.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_links', to='entities.publisher')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_links', to='entities.tactic')),
            ],
        ),
        migrations.CreateModel(
            name='TacticCreativeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_links', to='entities.creativetype')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_type_links', to='entities.tactic')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeTypeCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_type_links', to='entities.country')),
                ('creative_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_links', to='entities.creativetype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('creative_type', 'country'), name='pk_creative_type_countries')],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='entities_en_entity__73cf99_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_name'], name='entities_en_entity__8ee613_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['cost_center', 'entity_type'], name='entities_en_cost_ce_2a7afe_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['owner_advertiser', 'entity_type'], name='entities_en_owner_a_0f4595_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('id', 'entity_type'), name='ux_entities_id_type'),
        ),
        migrations.AddConstraint(
            model_name='advertiserentityblock',
            constraint=models.UniqueConstraint(fields=('advertiser', 'entity'), name='pk_advertiser_entity_blocks'),
        ),
        migrations.AddConstraint(
            model_name='goaleffort',
            constraint=models.UniqueConstraint(fields=('goal', 'effort'), name='pk_goal_efforts'),
        ),
        migrations.AddIndex(
            model_name='performancepricingmodel',
            index=models.Index(fields=['cost_center'], name='entities_pe_cost_ce_6e971f_idx'),
        ),
        migrations.AddIndex(
            model_name='performancepricingmodel',
            index=models.Index(fields=['payment_type'], name='entities_pe_payment_9bb299_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancepricingmodel',
            constraint=models.UniqueConstraint(fields=('id', 'entity_type'), name='ux_perf_pricing_models_id_type'),
        ),
        migrations.AddConstraint(
            model_name='countryperformancepricingmodel',
            constraint=models.UniqueConstraint(fields=('country', 'performance_pricing_model'), name='pk_countries_performance_pricing_models'),
        ),
        migrations.AddIndex(
            model_name='performancepricingmodelvalue',
            index=models.Index(fields=['performance_pricing_model'], name='entities_pe_perform_852eea_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancepricingmodelvalue',
            constraint=models.UniqueConstraint(fields=('id', 'entity_type'), name='ux_perf_pricing_models_value_id_type'),
        ),
        migrations.AddConstraint(
            model_name='performancepricingmodelvalue_link',
            constraint=models.UniqueConstraint(fields=('performance_pricing_model', 'performance_pricing_model_value'), name='pk_perf_pricing_models_values'),
        ),
        migrations.AddConstraint(
            model_name='categoryproduct',
            constraint=models.UniqueConstraint(fields=('category', 'product'), name='pk_category_products'),
        ),
        migrations.AddConstraint(
            model_name='productlanguage',
            constraint=models.UniqueConstraint(fields=('product', 'language'), name='pk_product_languages'),
        ),
        migrations.AddConstraint(
            model_name='goalpublisher',
            constraint=models.UniqueConstraint(fields=('goal', 'publisher'), name='pk_goal_publishers'),
        ),
        migrations.AddConstraint(
            model_name='publishertactic',
            constraint=models.UniqueConstraint(fields=('publisher', 'tactic'), name='pk_publishers_tactics'),
        ),
        migrations.AddConstraint(
            model_name='tacticcreativetype',
            constraint=models.UniqueConstraint(fields=('tactic', 'creative_type'), name='pk_tactic_creative_types'),
        ),
    ]
