# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='external ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='status')),
                ('total_budget_micros', models.BigIntegerField(verbose_name='total budget (micros)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'media plan',
                'verbose_name_plural': 'media plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=100, verbose_name='campaign name')),
                ('internal_campaign_name', models.CharField(max_length=100, verbose_name='internal campaign name')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='external ID')),
                ('landing_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='landing URL')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('total_budget_micros', models.BigIntegerField(verbose_name='total budget (micros)')),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='invoice reference')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='entities.category', verbose_name='category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='entities.language', verbose_name='language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='entities.product', verbose_name='product')),
                ('media_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.mediaplan', verbose_name='media plan')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(max_length=50, verbose_name='internal code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.advertiser', verbose_name='advertiser')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_plans', to='campaigns.project', verbose_name='project'),
        ),
        migrations.CreateModel(
            name='Subcampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('subcampaign_code', models.CharField(help_text='Format: AAYYMMNNNN (agency code + year + month + sequence)', max_length=255, unique=True, verbose_name='subcampaign code')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='objective')),
                ('city_geoname_id', models.IntegerField(verbose_name='city geoname ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_CREATIVES', 'Waiting for Creatives'), ('WAIT_FOR_OPS_APPROVAL', 'Wait for Ops Approval'), ('OPS_APPROVAL', 'Ops Approval'), ('WAIT_CLIENT', 'Wait Client'), ('APPROVED', 'Approved'), ('MEDIA_SETUP', 'Media Setup'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('REVIEW', 'Review'), ('CANCELLED', 'Cancelled'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=30, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcampaigns', to='campaigns.campaign', verbose_name='campaign')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.country', verbose_name='country')),
                ('creative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.creativetype', verbose_name='creative type')),
                ('effort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.effort', verbose_name='effort')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.goal', verbose_name='goal')),
                ('l11_custom4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l11custom4')),
                ('l13_custom5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l13custom5')),
                ('l15_custom6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l15custom6')),
                ('l16_custom7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l16custom7')),
                ('l17_custom8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l17custom8')),
                ('l19_custom9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l19custom9')),
                ('l20_custom10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l20custom10')),
                ('l5_custom1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l5custom1')),
                ('l8_custom2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l8custom2')),
                ('l9_custom3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcampaigns', to='entities.l9custom3')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.publisher', verbose_name='publisher')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaigns', to='entities.tactic', verbose_name='tactic')),
                ('trafficker_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trafficked_subcampaigns', to=settings.AUTH_USER_MODEL, verbose_name='trafficker')),
            ],
            options={
                'verbose_name': 'subcampaign',
                'verbose_name_plural': 'subcampaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcampaignVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='version number')),
                ('version_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='version name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_CREATIVES', 'Waiting for Creatives'), ('WAIT_FOR_OPS_APPROVAL', 'Wait for Ops Approval'), ('OPS_APPROVAL', 'Ops Approval'), ('WAIT_CLIENT', 'Wait Client'), ('APPROVED', 'Approved'), ('MEDIA_SETUP', 'Media Setup'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('REVIEW', 'Review'), ('CANCELLED', 'Cancelled'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=30, verbose_name='status')),
                ('unit_price_micros', models.BigIntegerField(verbose_name='unit price (micros)')),
                ('planned_units', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='planned units')),
                ('planned_budget_micros', models.BigIntegerField(verbose_name='planned budget (micros)')),
                ('is_unit_price_overwritten', models.BooleanField(default=False, help_text='True if the unit price was manually overridden by user', verbose_name='is unit price overwritten')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaign_versions', to='core.currency', verbose_name='currency')),
                ('media_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcampaign_versions', to='entities.mediaunittype', verbose_name='media unit type')),
                ('performance_pricing_model', models.ForeignKey(blank=True, help_text='Reference to the pricing model used for this version', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcampaign_versions', to='entities.performancepricingmodel', verbose_name='performance pricing model')),
                ('subcampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='campaigns.subcampaign', verbose_name='subcampaign')),
            ],
            options={
                'verbose_name': 'subcampaign version',
                'verbose_name_plural': 'subcampaign versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['category'], name='campaigns_c_categor_fa8f51_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['product'], name='campaigns_c_product_b0d5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['language'], name='campaigns_c_languag_22aa60_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('advertiser', 'internal_code'), name='ux_project_advertiser_code'),
        ),
        migrations.AddIndex(
            model_name='subcampaign',
            index=models.Index(fields=['trafficker_user'], name='campaigns_s_traffic_1e6c46_idx'),
        ),
        migrations.AddIndex(
            model_name='subcampaign',
            index=models.Index(fields=['status'], name='campaigns_s_status_23ceb1_idx'),
        ),
        migrations.AddIndex(
            model_name='subcampaign',
            index=models.Index(fields=['subcampaign_code'], name='campaigns_s_subcamp_02aea4_idx'),
        ),
        migrations.AddIndex(
            model_name='subcampaignversion',
            index=models.Index(fields=['media_unit_type'], name='campaigns_s_media_u_ebe5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='subcampaignversion',
            index=models.Index(fields=['status'], name='campaigns_s_status_b7396f_idx'),
        ),
        migrations.AddIndex(
            model_name='subcampaignversion',
            index=models.Index(fields=['performance_pricing_model'], name='campaigns_s_perform_980c1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcampaignversion',
            constraint=models.UniqueConstraint(fields=('subcampaign', 'version_number'), name='ux_subcampaign_version_sub_vn'),
        ),
    ]
