# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('data_type', models.CharField(choices=[('single_select', 'Single Select'), ('multi_select', 'Multi Select'), ('hierarchical', 'Hierarchical')], default='single_select', max_length=20, verbose_name='data type')),
                ('applies_to', models.CharField(choices=[('campaign', 'Campaign'), ('media_plan', 'Media Plan'), ('subcampaign', 'Subcampaign'), ('project', 'Project'), ('all', 'All Entities')], default='all', max_length=20, verbose_name='applies to')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_definitions', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'label definition',
                'verbose_name_plural': 'label definitions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabelLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level_number', models.PositiveSmallIntegerField(verbose_name='level number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('label_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='labels.labeldefinition', verbose_name='label definition')),
            ],
            options={
                'verbose_name': 'label level',
                'verbose_name_plural': 'label levels',
                'ordering': ['label_definition', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='LabelValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='external ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('label_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='labels.labeldefinition', verbose_name='label definition')),
                ('label_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='labels.labellevel', verbose_name='label level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='labels.labelvalue', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'label value',
                'verbose_name_plural': 'label values',
                'ordering': ['label_definition', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaign_labels', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='campaigns.campaign', verbose_name='campaign')),
                ('label_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='labels.labelvalue', verbose_name='label value')),
            ],
            options={
                'verbose_name': 'campaign label',
                'verbose_name_plural': 'campaign labels',
            },
        ),
        migrations.CreateModel(
            name='MediaPlanLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_media_plan_labels', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('label_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_plan_assignments', to='labels.labelvalue', verbose_name='label value')),
                ('media_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='campaigns.mediaplan', verbose_name='media plan')),
            ],
            options={
                'verbose_name': 'media plan label',
                'verbose_name_plural': 'media plan labels',
            },
        ),
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_labels', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('label_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='labels.labelvalue', verbose_name='label value')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='campaigns.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project label',
                'verbose_name_plural': 'project labels',
            },
        ),
        migrations.CreateModel(
            name='SubcampaignLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subcampaign_labels', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('label_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcampaign_assignments', to='labels.labelvalue', verbose_name='label value')),
                ('subcampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='campaigns.subcampaign', verbose_name='subcampaign')),
            ],
            options={
                'verbose_name': 'subcampaign label',
                'verbose_name_plural': 'subcampaign labels',
            },
        ),
        migrations.AddIndex(
            model_name='labeldefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='labels_labe_tenant__3aa880_idx'),
        ),
        migrations.AddIndex(
            model_name='labeldefinition',
            index=models.Index(fields=['applies_to'], name='labels_labe_applies_897625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labeldefinition',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='labellevel',
            unique_together={('label_definition', 'level_number')},
        ),
        migrations.AddIndex(
            model_name='labelvalue',
            index=models.Index(fields=['label_definition', 'is_active'], name='labels_labe_label_d_69dc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='labelvalue',
            index=models.Index(fields=['parent'], name='labels_labe_parent__8e6b09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labelvalue',
            unique_together={('label_definition', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignlabel',
            unique_together={('campaign', 'label_value')},
        ),
        migrations.AlterUniqueTogether(
            name='mediaplanlabel',
            unique_together={('media_plan', 'label_value')},
        ),
        migrations.AlterUniqueTogether(
            name='projectlabel',
            unique_together={('project', 'label_value')},
        ),
        migrations.AlterUniqueTogether(
            name='subcampaignlabel',
            unique_together={('subcampaign', 'label_value')},
        ),
    ]
