# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCountry',
            fields=[
                ('iso_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO code')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='GeoName ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone_prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='phone prefix')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'geo_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoState',
            fields=[
                ('geoname_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='GeoName ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('country', models.ForeignKey(db_column='country_iso_code', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geo.geocountry', verbose_name='country')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
                'db_table': 'geo_state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('geoname_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='GeoName ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('timezone_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='timezone code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('state', models.ForeignKey(blank=True, db_column='state_geoname_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.geostate', verbose_name='state')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'geo_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoCityCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('city', models.ForeignKey(db_column='city_geoname_id', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='geo.geocity', verbose_name='city')),
                ('country', models.ForeignKey(db_column='country_iso_code', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.geocountry', verbose_name='country')),
            ],
            options={
                'verbose_name': 'city-country mapping',
                'verbose_name_plural': 'city-country mappings',
                'db_table': 'geo_city_country',
                'constraints': [models.UniqueConstraint(fields=('city', 'country'), name='ux_geo_city_country')],
            },
        ),
        migrations.CreateModel(
            name='GeoPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('city', models.ForeignKey(db_column='city_geoname_id', on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='geo.geocity', verbose_name='city')),
            ],
            options={
                'verbose_name': 'postal code',
                'verbose_name_plural': 'postal codes',
                'db_table': 'geo_postal_code',
                'constraints': [models.UniqueConstraint(fields=('postal_code', 'city'), name='ux_geo_postal_code_postal_city')],
            },
        ),
    ]
