# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('internal_code', models.CharField(max_length=50, verbose_name='internal code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code_subcampaign', models.CharField(help_text='4-character code for subcampaigns', max_length=4, verbose_name='subcampaign code')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('address_city_geoname_id', models.IntegerField(blank=True, null=True, verbose_name='city geoname ID')),
                ('address_country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='country code')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='effective from')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='effective to')),
            ],
            options={
                'verbose_name': 'system parameter',
                'verbose_name_plural': 'system parameters',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='applied at')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'system version',
                'verbose_name_plural': 'system versions',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code_prefix', models.CharField(help_text='4-character prefix for generating codes', max_length=4, unique=True, verbose_name='code prefix')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('utc_offset', models.CharField(max_length=6, verbose_name='UTC offset')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'timezone',
                'verbose_name_plural': 'timezones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('internal_code', models.CharField(max_length=50, verbose_name='internal code')),
                ('payment_terms_days', models.IntegerField(blank=True, null=True, verbose_name='payment terms (days)')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='billing email')),
                ('legal_entity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='legal entity name')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='tax ID')),
                ('tax_country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='tax country code')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('address_city_geoname_id', models.IntegerField(blank=True, null=True, verbose_name='city geoname ID')),
                ('address_country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='country code')),
                ('billing_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='billing contact name')),
                ('billing_contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='billing contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.agency', verbose_name='agency')),
                ('default_currency', models.ForeignKey(db_column='default_currency_code', on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='core.currency', verbose_name='default currency')),
                ('timezone', models.ForeignKey(blank=True, db_column='timezone_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='core.timezone', verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'cost center',
                'verbose_name_plural': 'cost centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='external ID')),
                ('internal_code', models.CharField(max_length=50, verbose_name='internal code')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('address_city_geoname_id', models.IntegerField(blank=True, null=True, verbose_name='city geoname ID')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact name')),
                ('contact_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact position')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact phone')),
                ('contact_phone_alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='alt contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('contact_email_alt', models.EmailField(blank=True, max_length=254, null=True, verbose_name='alt contact email')),
                ('payment_terms_days_override', models.IntegerField(blank=True, null=True, verbose_name='payment terms override')),
                ('billing_email_override', models.EmailField(blank=True, max_length=254, null=True, verbose_name='billing email override')),
                ('credit_limit_amount_micros', models.BigIntegerField(blank=True, null=True, verbose_name='credit limit (micros)')),
                ('credit_risk_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='credit risk level')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=30, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.costcenter', verbose_name='cost center')),
                ('currency_show', models.ForeignKey(db_column='currency_code_show', on_delete=django.db.models.deletion.PROTECT, related_name='clients_display', to='core.currency', verbose_name='display currency')),
                ('timezone', models.ForeignKey(blank=True, db_column='timezone_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.timezone', verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='agency',
            name='timezone',
            field=models.ForeignKey(blank=True, db_column='timezone_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='core.timezone', verbose_name='timezone'),
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('internal_code', models.CharField(max_length=50, verbose_name='internal code')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='tax ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('address_city_geoname_id', models.IntegerField(blank=True, null=True, verbose_name='city geoname ID')),
                ('address_country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='country code')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact phone')),
                ('contact_phone_alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='alt contact phone')),
                ('contact_email_alt', models.EmailField(blank=True, max_length=254, null=True, verbose_name='alt contact email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=30, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='core.client', verbose_name='client')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisers', to='core.industry', verbose_name='industry')),
            ],
            options={
                'verbose_name': 'advertiser',
                'verbose_name_plural': 'advertisers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('client', 'name'), name='ux_advertiser_client_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('agency', 'code'), name='ux_cost_center_agency_code'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('cost_center', 'name'), name='ux_client_cost_center_name'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_code'), name='ux_agency_tenant_code'),
        ),
    ]
