# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortalSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_campaigns', models.BooleanField(default=True, verbose_name='can view campaigns')),
                ('can_view_media_plans', models.BooleanField(default=True, verbose_name='can view media plans')),
                ('can_view_budgets', models.BooleanField(default=False, verbose_name='can view budgets')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='can view reports')),
                ('can_download_reports', models.BooleanField(default=True, verbose_name='can download reports')),
                ('can_approve', models.BooleanField(default=True, verbose_name='can approve')),
                ('can_comment', models.BooleanField(default=True, verbose_name='can comment')),
                ('welcome_message', models.TextField(blank=True, verbose_name='welcome message')),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/', verbose_name='custom logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='primary color')),
                ('email_on_new_campaign', models.BooleanField(default=True, verbose_name='email on new campaign')),
                ('email_on_approval_request', models.BooleanField(default=True, verbose_name='email on approval request')),
                ('email_on_status_change', models.BooleanField(default=True, verbose_name='email on status change')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to='core.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'client portal settings',
                'verbose_name_plural': 'client portal settings',
            },
        ),
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='has attachments')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='campaigns.campaign', verbose_name='campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='core.client', verbose_name='client')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_portal_messages', to=settings.AUTH_USER_MODEL, verbose_name='read by')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_portal_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'portal message',
                'verbose_name_plural': 'portal messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalMessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.FileField(upload_to='portal/attachments/', verbose_name='file')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.portalmessage', verbose_name='message')),
            ],
            options={
                'verbose_name': 'portal message attachment',
                'verbose_name_plural': 'portal message attachments',
            },
        ),
        migrations.CreateModel(
            name='PortalActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_campaign', 'View Campaign'), ('view_media_plan', 'View Media Plan'), ('view_report', 'View Report'), ('download_report', 'Download Report'), ('approve', 'Approve'), ('reject', 'Reject'), ('comment', 'Comment'), ('message', 'Message')], max_length=30, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='entity type')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='entity ID')),
                ('entity_name', models.CharField(blank=True, max_length=255, verbose_name='entity name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activities', to='core.client', verbose_name='client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activities', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'portal activity log',
                'verbose_name_plural': 'portal activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='portal_port_user_id_ad2bfe_idx'), models.Index(fields=['client', 'created_at'], name='portal_port_client__2fa247_idx')],
            },
        ),
    ]
