# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('subcampaign', 'Subcampaign'), ('subcampaign_version', 'Subcampaign Version'), ('subcampaign_payment_type', 'Subcampaign Payment Type'), ('creative_assignment', 'Creative Assignment'), ('creative_approval', 'Creative Approval'), ('budget_hold', 'Budget Hold'), ('month_closure', 'Month Closure'), ('approval_request', 'Approval Request'), ('approval_step_instance', 'Approval Step Instance'), ('approval_action', 'Approval Action'), ('pricing_adjustment_rule', 'Pricing Adjustment Rule'), ('performance_pricing_model', 'Performance Pricing Model'), ('project', 'Project'), ('media_plan', 'Media Plan'), ('campaign', 'Campaign'), ('client', 'Client'), ('advertiser', 'Advertiser'), ('cost_center', 'Cost Center')], max_length=50, verbose_name='entity type')),
                ('entity_id', models.UUIDField(help_text='UUID of the affected entity', verbose_name='entity ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('state_changed', 'State Changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('pricing_overridden', 'Pricing Overridden'), ('fee_overridden', 'Fee Overridden'), ('perm_changed', 'Permission Changed'), ('budget_hold_created', 'Budget Hold Created'), ('budget_hold_closed', 'Budget Hold Closed'), ('month_closure_created', 'Month Closure Created'), ('month_closure_closed', 'Month Closure Closed'), ('month_closure_reopened', 'Month Closure Reopened')], max_length=30, verbose_name='action')),
                ('description', models.TextField(help_text='Human-readable description of the change', verbose_name='description')),
                ('old_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='old state')),
                ('new_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='new state')),
                ('extra_data', models.JSONField(blank=True, help_text='Additional context data in JSON format', null=True, verbose_name='extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='user agent')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['created_by'], name='audit_audit_created_35c32f_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['entity_type', 'action'], name='audit_audit_entity__f9270a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('subcampaign', 'Subcampaign'), ('subcampaign_version', 'Subcampaign Version'), ('subcampaign_payment_type', 'Subcampaign Payment Type'), ('creative_assignment', 'Creative Assignment'), ('creative_approval', 'Creative Approval'), ('budget_hold', 'Budget Hold'), ('month_closure', 'Month Closure'), ('approval_request', 'Approval Request'), ('approval_step_instance', 'Approval Step Instance'), ('approval_action', 'Approval Action'), ('pricing_adjustment_rule', 'Pricing Adjustment Rule'), ('performance_pricing_model', 'Performance Pricing Model'), ('project', 'Project'), ('media_plan', 'Media Plan'), ('campaign', 'Campaign'), ('client', 'Client'), ('advertiser', 'Advertiser'), ('cost_center', 'Cost Center')], max_length=50, verbose_name='entity type')),
                ('entity_id', models.UUIDField(help_text='UUID of the affected entity', verbose_name='entity ID')),
                ('field_name', models.CharField(help_text='Name of the field that was changed (e.g., planned_budget_micros)', max_length=100, verbose_name='field name')),
                ('old_value_micros', models.BigIntegerField(blank=True, help_text='Previous value (null if field was empty)', null=True, verbose_name='old value (micros)')),
                ('new_value_micros', models.BigIntegerField(help_text='New value after the change', verbose_name='new value (micros)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change (required for manual overrides)', null=True, verbose_name='reason')),
                ('is_manual_override', models.BooleanField(default=False, help_text='True if this was a manual override by user', verbose_name='is manual override')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('entity_state', models.CharField(blank=True, help_text='State of the entity at the time of change', max_length=50, null=True, verbose_name='entity state')),
                ('pricing_model_id', models.UUIDField(blank=True, help_text='ID of the pricing model used for calculation', null=True, verbose_name='pricing model ID')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
            ],
            options={
                'verbose_name': 'budget change log',
                'verbose_name_plural': 'budget change logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_budge_entity__947b56_idx'), models.Index(fields=['field_name'], name='audit_budge_field_n_cab833_idx'), models.Index(fields=['changed_by'], name='audit_budge_changed_960e26_idx'), models.Index(fields=['changed_at'], name='audit_budge_changed_b76ed1_idx'), models.Index(fields=['is_manual_override'], name='audit_budge_is_manu_3f8e25_idx')],
            },
        ),
    ]
