# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('entity_type', models.CharField(choices=[('campaign', 'Campaign'), ('media_plan', 'Media Plan'), ('subcampaign', 'Subcampaign'), ('project', 'Project')], max_length=20, verbose_name='entity type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'workflow definition',
                'verbose_name_plural': 'workflow definitions',
                'ordering': ['entity_type', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('state_type', models.CharField(choices=[('initial', 'Initial'), ('intermediate', 'Intermediate'), ('final', 'Final')], default='intermediate', max_length=20, verbose_name='state type')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_editable', models.BooleanField(default=True, help_text='Can entity be edited in this state?', verbose_name='is editable')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires approval')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflowdefinition', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow state',
                'verbose_name_plural': 'workflow states',
                'ordering': ['workflow', 'display_order'],
                'unique_together': {('workflow', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowdefinition', verbose_name='workflow')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='workflows.workflowstate', verbose_name='current state')),
            ],
            options={
                'verbose_name': 'workflow instance',
                'verbose_name_plural': 'workflow instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='requires comment')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires approval')),
                ('auto_execute', models.BooleanField(default=False, help_text='Execute automatically when conditions are met', verbose_name='auto execute')),
                ('notify_users', models.BooleanField(default=True, verbose_name='notify users')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_transitions', to='auth.group', verbose_name='allowed groups')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstate', verbose_name='from state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstate', verbose_name='to state')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowdefinition', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow transition',
                'verbose_name_plural': 'workflow transitions',
                'ordering': ['workflow', 'from_state__display_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workflowinstance', verbose_name='instance')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_from', to='workflows.workflowstate', verbose_name='from state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_to', to='workflows.workflowstate', verbose_name='to state')),
                ('transition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='workflows.workflowtransition', verbose_name='transition')),
            ],
            options={
                'verbose_name': 'workflow history',
                'verbose_name_plural': 'workflow histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('min_approvals', models.PositiveSmallIntegerField(default=1, verbose_name='minimum approvals')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('response_comment', models.TextField(blank=True, verbose_name='response comment')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('required_approvers', models.ManyToManyField(blank=True, related_name='required_approvals', to=settings.AUTH_USER_MODEL, verbose_name='required approvers')),
                ('required_groups', models.ManyToManyField(blank=True, related_name='required_approvals', to='auth.group', verbose_name='required groups')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_approvals', to=settings.AUTH_USER_MODEL, verbose_name='responded by')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflows.workflowinstance', verbose_name='workflow instance')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflows.workflowtransition', verbose_name='transition')),
            ],
            options={
                'verbose_name': 'approval request',
                'verbose_name_plural': 'approval requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(verbose_name='is approved')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('responded_at', models.DateTimeField(auto_now_add=True, verbose_name='responded at')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workflows.approvalrequest', verbose_name='approval request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_responses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'approval response',
                'verbose_name_plural': 'approval responses',
                'ordering': ['-responded_at'],
                'unique_together': {('approval_request', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('state_changed', 'State Changed'), ('approval_required', 'Approval Required'), ('approval_received', 'Approval Received'), ('rejection_received', 'Rejection Received'), ('deadline_approaching', 'Deadline Approaching'), ('deadline_passed', 'Deadline Passed')], max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email sent at')),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.approvalrequest', verbose_name='approval request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflowinstance', verbose_name='workflow instance')),
            ],
            options={
                'verbose_name': 'workflow notification',
                'verbose_name_plural': 'workflow notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='workflows_w_user_id_e2bb40_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_9e540a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow', 'from_state', 'to_state')},
        ),
    ]
