# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('alert_type', models.CharField(choices=[('budget_threshold', 'Budget Threshold'), ('campaign_ending', 'Campaign Ending'), ('approval_pending', 'Approval Pending'), ('performance_drop', 'Performance Drop'), ('deadline_approaching', 'Deadline Approaching'), ('custom', 'Custom')], max_length=30, verbose_name='alert type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='severity')),
                ('conditions', models.JSONField(default=dict, help_text='Alert trigger conditions', verbose_name='conditions')),
                ('notify_email', models.BooleanField(default=True, verbose_name='notify email')),
                ('notify_inapp', models.BooleanField(default=True, verbose_name='notify in-app')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='last triggered at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='triggered at')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='is acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.alert', verbose_name='alert')),
            ],
            options={
                'verbose_name': 'alert history',
                'verbose_name_plural': 'alert histories',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('role', models.CharField(choices=[('planner', 'Planner'), ('operations', 'Operations'), ('finance', 'Finance'), ('accounts', 'Accounts'), ('admin', 'Admin'), ('client', 'Client'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='role')),
                ('layout', models.JSONField(default=list, help_text='Dashboard layout configuration', verbose_name='layout')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_system', models.BooleanField(default=False, help_text='System dashboards cannot be deleted', verbose_name='is system')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card'), ('chart_line', 'Line Chart'), ('chart_bar', 'Bar Chart'), ('chart_pie', 'Pie Chart'), ('table', 'Table'), ('list', 'List'), ('calendar', 'Calendar'), ('progress', 'Progress Bar'), ('alerts', 'Alerts'), ('tasks', 'Tasks')], max_length=20, verbose_name='widget type')),
                ('config', models.JSONField(default=dict, help_text='Widget configuration', verbose_name='config')),
                ('data_source', models.CharField(help_text='API endpoint or data source identifier', max_length=100, verbose_name='data source')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('position_x', models.PositiveSmallIntegerField(default=0, verbose_name='position X')),
                ('position_y', models.PositiveSmallIntegerField(default=0, verbose_name='position Y')),
                ('width', models.PositiveSmallIntegerField(default=4, verbose_name='width')),
                ('height', models.PositiveSmallIntegerField(default=3, verbose_name='height')),
                ('refresh_interval', models.PositiveIntegerField(default=0, help_text='Refresh interval in seconds (0 = no auto refresh)', verbose_name='refresh interval')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard', verbose_name='dashboard')),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(choices=[('campaign_performance', 'Campaign Performance'), ('budget_overview', 'Budget Overview'), ('media_plan_summary', 'Media Plan Summary'), ('project_status', 'Project Status'), ('team_workload', 'Team Workload'), ('client_overview', 'Client Overview'), ('custom', 'Custom Report')], max_length=30, verbose_name='report type')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Report filter configuration', verbose_name='filters')),
                ('columns', models.JSONField(blank=True, default=list, help_text='Selected columns for the report', verbose_name='columns')),
                ('sorting', models.JSONField(blank=True, default=list, verbose_name='sorting')),
                ('grouping', models.JSONField(blank=True, default=list, verbose_name='grouping')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='is scheduled')),
                ('schedule_frequency', models.CharField(blank=True, help_text='daily, weekly, monthly', max_length=20, verbose_name='schedule frequency')),
                ('schedule_recipients', models.JSONField(blank=True, default=list, verbose_name='schedule recipients')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last sent at')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='shared with')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved report',
                'verbose_name_plural': 'saved reports',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=10, verbose_name='format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('config', models.JSONField(default=dict, verbose_name='config')),
                ('file', models.FileField(blank=True, null=True, upload_to='report_exports/', verbose_name='file')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='row count')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports.savedreport', verbose_name='saved report')),
            ],
            options={
                'verbose_name': 'report export',
                'verbose_name_plural': 'report exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
