# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EosTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('scope_level', models.CharField(choices=[('tenant', 'Tenant'), ('agency', 'Agency'), ('cost_center', 'Cost Center'), ('client', 'Client'), ('advertiser', 'Advertiser'), ('project', 'Project'), ('media_plan', 'Media Plan')], max_length=30, verbose_name='scope level')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.advertiser', verbose_name='advertiser')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.agency', verbose_name='agency')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.client', verbose_name='client')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.costcenter', verbose_name='cost center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('media_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='campaigns.mediaplan', verbose_name='media plan')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='campaigns.project', verbose_name='project')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EosTaggedItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50, verbose_name='entity type')),
                ('entity_id', models.UUIDField(verbose_name='entity ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tags.eostag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tagged item',
                'verbose_name_plural': 'tagged items',
            },
        ),
        migrations.AddConstraint(
            model_name='eostag',
            constraint=models.UniqueConstraint(fields=('scope_level', 'tenant', 'slug'), name='ux_eos_tag_scope_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='eostaggeditem',
            index=models.Index(fields=['entity_type', 'entity_id'], name='tags_eostag_entity__9d70b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='eostaggeditem',
            constraint=models.UniqueConstraint(fields=('tag', 'entity_type', 'entity_id'), name='ux_eos_tagged_item_tag_entity'),
        ),
    ]
