# Generated by Django 5.2.9 on 2025-12-26 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('media_unit_type', 'Media Unit Type'), ('fee', 'Fee')], max_length=20, verbose_name='payment type')),
                ('fee_type', models.CharField(blank=True, choices=[('PCT', 'Percentage'), ('FLAT', 'Flat Amount')], max_length=10, null=True, verbose_name='fee type')),
                ('fee_value_micros', models.BigIntegerField(blank=True, null=True, verbose_name='fee value (micros)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('advertiser', models.ForeignKey(blank=True, help_text='Optional override for specific advertiser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_overrides', to='core.advertiser', verbose_name='advertiser override')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.costcenter', verbose_name='cost center')),
                ('media_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='entities.mediaunittype', verbose_name='media unit type')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'indexes': [models.Index(fields=['cost_center'], name='payments_pa_cost_ce_822f6d_idx'), models.Index(fields=['advertiser'], name='payments_pa_adverti_3e69da_idx'), models.Index(fields=['payment_type'], name='payments_pa_payment_c8697a_idx')],
                'constraints': [models.UniqueConstraint(fields=('cost_center', 'advertiser', 'payment_type', 'media_unit_type', 'fee_type', 'fee_value_micros'), name='ux_payment_methods_signature')],
            },
        ),
        migrations.CreateModel(
            name='PricingAdjustmentRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_kind', models.CharField(choices=[('cost_center', 'Cost Center'), ('client', 'Client'), ('advertiser', 'Advertiser')], max_length=20, verbose_name='target kind')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('payment_method', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid'), ('CREDIT', 'Credit')], max_length=20, null=True, verbose_name='payment method')),
                ('is_adjustment_value_micros_overwritten', models.BooleanField(default=False, help_text='True if the adjustment value was manually overridden', verbose_name='is adjustment value overwritten')),
                ('adjustment_kind', models.CharField(choices=[('PCT_OF_BASE_MICROS', 'Percentage of Base (Micros)'), ('ABS_MICROS', 'Absolute (Micros)'), ('OVERRIDE_MICROS', 'Override (Micros)')], max_length=30, verbose_name='adjustment kind')),
                ('adjustment_value_micros', models.BigIntegerField(verbose_name='adjustment value (micros)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_adjustment_rules', to='core.advertiser', verbose_name='advertiser')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_adjustment_rules', to='core.client', verbose_name='client')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_adjustment_rules', to='core.costcenter', verbose_name='cost center')),
            ],
            options={
                'verbose_name': 'pricing adjustment rule',
                'verbose_name_plural': 'pricing adjustment rules',
                'indexes': [models.Index(fields=['target_kind'], name='payments_pr_target__c7844b_idx'), models.Index(fields=['cost_center'], name='payments_pr_cost_ce_317215_idx'), models.Index(fields=['client'], name='payments_pr_client__6428d0_idx'), models.Index(fields=['advertiser'], name='payments_pr_adverti_72b094_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubcampaignPaymentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('fee_type', models.CharField(blank=True, choices=[('PCT', 'Percentage'), ('FLAT', 'Flat Amount'), ('ABS', 'Absolute')], max_length=10, null=True, verbose_name='fee type')),
                ('fee_value', models.BigIntegerField(blank=True, null=True, verbose_name='fee value')),
                ('is_fee_value_overwritten', models.BooleanField(default=False, help_text='True if the fee value was manually overridden by user', verbose_name='is fee value overwritten')),
                ('subcampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='campaigns.subcampaign', verbose_name='subcampaign')),
            ],
            options={
                'verbose_name': 'subcampaign payment type',
                'verbose_name_plural': 'subcampaign payment types',
                'indexes': [models.Index(fields=['subcampaign'], name='payments_su_subcamp_af47a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('subcampaign', 'start_date', 'end_date'), name='ux_subcampaign_payment_type_range')],
            },
        ),
    ]
